### ISSUE TITLE
Image captions

### ISSUE THREAD

**Issue by ihougland** [kthornbloom/JACKRABBIT-CMS#41] opened 2015-06-16 15:47 UTC
Consider adding the ability to easily add captions to images

**Comment by ihougland** [comment] 2015-06-16 20:38
For HoCo, I'm thinking this may not be as big of a deal as I had initially thought. Still might be nice though.

**Comment by kthornbloom** [comment] 2015-07-03 17:16
Closing for now. If we used captions, they would be in some sort of wrapper around the image. The issue is that if the user drags the image to move it, it would get dragged out of the wrapper leaving behind the caption. No solution for this yet.

**Closed by kthornbloom** 2015-07-03 17:16 UTC
Labels: Essential Enhancement
